### ISSUE TITLE
run custom engine fail

### ISSUE THREAD

**Issue by fanweiya** [PICOPON/yolov5_engine#2]
I use  up-to-date yolov5 export engine,but run your code fail.
Your GPU device:  NVIDIA GeForce RTX 2080 Ti
[05/14/2022-15:15:41] [TRT] [I] [MemUsageChange] Init CUDA: CPU +302, GPU +0, now: CPU 16323, GPU 1402 (MiB)
[05/14/2022-15:15:41] [TRT] [I] Loaded engine size: 34 MiB
[05/14/2022-15:15:41] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +34, now: CPU 0, GPU 34 (MiB)
[05/14/2022-15:15:41] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +35, now: CPU 0, GPU 69 (MiB)
bingding: images (1, 3, 640, 640)
bingding: output (1, 25200, 7)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "F:\Anaconda3\envs\cellpose\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "yolov5pred.py", line 492, in run
    batch_image_raw, use_time = self.yolov5_wrapper.infer(self.yolov5_wrapper.get_raw_image_zeros())
  File "yolov5pred.py", line 159, in infer
    cuda.memcpy_dtoh_async(host_outputs[3], cuda_outputs[3], stream)
IndexError: list index out of range
Start image predict...

**Comment by whgsh** [comment]
same problem, have u solved it yet?

**Comment by PICOPON** [comment]
Sorry, please try to make a small change to the .export.py file, add the following at the top of the function export_onnx， 
def export_onnx(model, im, file, opset, train, dynamic, simplify, prefix=colorstr('ONNX:')):
    wtxt = open('class.names', 'w')
    for name in model.names:
        wtxt.write(name+'\n')
    wtxt.close()
    if not dynamic:
        f = os.path.splitext(file)[0] + '.onnx'
        torch.onnx.export(model, im, f, verbose=False, opset_version=12, input_names=['images'], output_names=['output'])
    else:
        f = os.path.splitext(file)[0] + '_dynamic.onnx'
        torch.onnx.export(model, im, f, verbose=False, opset_version=12, input_names=['images'],
                          output_names=['output'], dynamic_axes={'images': {0: 'batch', 2: 'height', 3: 'width'},  # shape(1,3,640,640)
                                        'output': {0: 'batch', 1: 'anchors'}  # shape(1,25200,85)
                                        })
    ....
Then try to use this .onnx file.

**Comment by PICOPON** [comment]
Sorry, please try to make a small change to the .export.py file, add the following at the top of the function export_onnx， 
def export_onnx(model, im, file, opset, train, dynamic, simplify, prefix=colorstr('ONNX:')):
    wtxt = open('class.names', 'w')
    for name in model.names:
        wtxt.write(name+'\n')
    wtxt.close()
    if not dynamic:
        f = os.path.splitext(file)[0] + '.onnx'
        torch.onnx.export(model, im, f, verbose=False, opset_version=12, input_names=['images'], output_names=['output'])
    else:
        f = os.path.splitext(file)[0] + '_dynamic.onnx'
        torch.onnx.export(model, im, f, verbose=False, opset_version=12, input_names=['images'],
                          output_names=['output'], dynamic_axes={'images': {0: 'batch', 2: 'height', 3: 'width'},  # shape(1,3,640,640)
                                        'output': {0: 'batch', 1: 'anchors'}  # shape(1,25200,85)
                                        })
    ....
